### ISSUE TITLE
Cite Mustache at README

### ISSUE THREAD

**Issue by ppKrauss** [squirrellyjs/squirrelly#109]
Hi, is interesting to cite inspiration, similarities and differences with [Mustache](https://mustache.github.io/).

**Comment by nebrelbug** [comment]
@ppKrauss that's a great idea! I'd also like to compare it with Handlebars. Would you be interested in making a pull request with the changes?

**Comment by nebrelbug** [comment]
@ppKrauss I'm going to include this in the docs website :)
