### ISSUE TITLE
Parsing error with escaped single quotes on template

### ISSUE THREAD

**Issue by tabarra** [squirrellyjs/squirrelly#118]
**Describe the bug**
When trying to render a template that contains an escaped single quote (`\'`) squirrelly throws a SyntaxError.

**To Reproduce**
Consider the following code:
```javascript
const sqrl = require('squirrelly');
let tpl = `aaa\\'bbb`;
console.log(sqrl.Render(tpl, {}));
```

**Expected Output**
```
aaa\'bbb
```

**Screenshots**
https://i.imgur.com/xTvEhlL.png

**Additional context**
Tested on v7.2.1 and v7.1.3

**Comment by nebrelbug** [comment]
Alrighty @tabarra, this should be fixed with release `7.3.0` :smiley:

Let me know if this works! 👍 

I was also able to reduce the minified size of Squirrelly to 5kb minified and 2.2kb minzipped with the latest release (https://bundlephobia.com/result?p=squirrelly@7.3.0)
