### ISSUE TITLE
Site: Playground page breaks

### ISSUE THREAD

**Issue by fatganz** [squirrellyjs/squirrelly#135]
**Describe the bug**
When inserting potentially invalid template whole Playground page breaks. 

**To Reproduce**
1. Go to the playground page
2. insert the following snippet ```{{if(htmlstuff)}}test{{/if}}```
3. whole playground page is broken

**Expected behavior**
The playground page shouldn't break because people are trying to learn new things there. It should be safe for them to insert anything and the page should remain functional so they can identify where the error is in their code and fix it. For the project promotion reasons please make sure playground never breaks :)

**Comment by nebrelbug** [comment]
@fatganz so sorry - I'll work to fix this issue. In the meantime, you can use: https://raw.githack.com/squirrellyjs/squirrelly/master/demo.html

**Comment by fatganz** [comment]
Thanks for the quick reply and workaround! Not sure if this is an appropriate place, but thanks for keeping project alive.

**Comment by nebrelbug** [comment]
I've updated the Playground page, so closing now :smiley:
