### ISSUE TITLE
Link to benchmarks that can run in-browser

### ISSUE THREAD

**Issue by nebrelbug** [squirrellyjs/squirrelly#14]
I've written some benchmarks here: [https://github.com/nebrelbug/squirrelly-benchmarks](https://github.com/nebrelbug/squirrelly-benchmarks) but there aren't any benchmarks that you can run in the browser.

A good benchmark would include tests of:
- The time it takes to Precompile a Squirrelly template
- The time it takes to render a Precompiled template
- The time it takes for other template engines to render/precompile an equivalent template.

**Comment by Artistic18** [comment]
Can you please elaborate what we have to do?

**Comment by matkinson89** [comment]
Is this issue still open to work on?

**Comment by nebrelbug** [comment]
@matkinson89 yes, it would be wonderful if you wanted to work on it.

**Comment by dhuang612** [comment]
Hi,

I would be interested in working on this.
Do you mean benchmarks like this one?
https://github.com/v8/web-tooling-benchmark

**Comment by nebrelbug** [comment]
@dhuang612 exactly! Here are some resources you could potentially use:

- https://aui.github.io/art-template/rendering-test/
- https://github.com/rstacruz/benchmarkjs-runner
  - You'd probably need to update this

Let me know how this goes :smiley:

**Comment by nebrelbug** [comment]
I've added browser benchmarks, so I'll close this now.
