### ISSUE TITLE
Render breaks when using some custom tags

### ISSUE THREAD

**Issue by SomaticIT** [squirrellyjs/squirrelly#146]
**Describe the bug**
When using some custom tags, the whole template engine breaks.
1. Not important: `["[", "]"]` breaks because it should be escaped,
2. Important: `["\\$\\(", "\\)"]` breaks because parens are interpreted by squirrelly.

**To Reproduce**
1. Configure: `Sqrl.defaultConfig = ["\\$\\(", "\\)"];`
2. Create template: `const template = "Data: $(test)";`
3. Call function: `Sqrl.render(template, { test: "value" });`
4. Look at error :)

**Expected behavior**
Render result should be: `Data: value`

**Package & Environment Details**
 - Environment: Browser
 - Version: 8.0.0-beta.5

**Additional context**
I develop a software that already use the syntax `$(property)` for its users. We built a very simple template engine that need to evolve. We selected your project to replace our template engine with something far more powerful.

I love your project as it's well developped, light and fast. I would be very happy to be able to run your project in my software.

Do you think it's possible?

Thanks

**Comment by nebrelbug** [comment]
Hi @SomaticIT! Glad to hear you like this project! Unfortunately, it's not going to be possible to use `(`, `|`, or `=>` inside of the closing delimiters. I looked for a while at possibilities, but it would just be too complex.

Could you just slightly change the delimiters?

Example:
```js
Sqrl.defaultConfig.tags = ["\\${", "}"]
// $ has to be escaped because it's a RegExp special char

const template = "Hi ${it.name}"

Sqrl.render(template, { name: "@SomaticIT" })
// "Hi @SomaticIT"
```
