### ISSUE TITLE
Activating async causes the loop helpers to return [object Promise]

### ISSUE THREAD

**Issue by adriangith** [squirrellyjs/squirrelly#149]
**Bug**
Setting `async: true` when calling `Sqrl.render` causes the `foreach` and `each` helpers to return `[object Promise]`

**Expected behavior**
Should return the text within the helper blocks

**Package & Environment Details**
- Version 8: Beta 8

**Comment by nebrelbug** [comment]
Hi @adriangith, thanks for reporting the issue! This was a problem with Squirrelly's async implementation. I actually decided to just rewrite async handling, and I'll hopefully push the fixes tomorrow :smiley:

**Comment by nebrelbug** [comment]
Hi @adriangith, I just realized I forgot to respond! Just so you know, newer versions of Squirrelly 8 have this problem fixed :)
