### ISSUE TITLE
Missing "Get started" page on squirrelly.js.org (current)

### ISSUE THREAD

**Issue by corzani** [squirrellyjs/squirrelly#171]
Clicking on "Get Started" from the page "https://squirrelly.js.org/" gives a 404 page.

**Comment by nebrelbug** [comment]
@corzani thanks for catching this!

**Comment by nebrelbug** [comment]
Just fixed this :)

**Comment by corzani** [comment]
> @corzani thanks for catching this!

@nebrelbug Thanks to you
