### ISSUE TITLE
Use passed data object as root

### ISSUE THREAD

**Issue by kerosin** [squirrellyjs/squirrelly#188]
**Is your feature request related to a problem? Please describe.**
It seems unnecessary for template string authors to add a variable name for the given data object.

**Describe the solution you'd like**
It would be great to use data objects without the need of a variable name:
```
var myTemplate = "Hi, my name is {{name}}";
Sqrl.render(myTemplate, { name: "Johnny Appleseed" });
```
This of course would make it impossible to access something like a global context, but this might be desired.
It would be great to globally configure if a variable name is necesarry, e.g. via config
```
{
varName: '' // or null
}
```

**Comment by nebrelbug** [comment]
Hi @kerosin, thanks for the question!

This is possible by setting the configuration option `useWith` to `true`.

Example:

```js
var myTemplate = "Hi, my name is {{name}}";
Sqrl.render(myTemplate, { name: "Johnny Appleseed" }, {useWith: true});
```

I should probably update the documentation to explain this :smiley: 

Hope this helps!

**Comment by kerosin** [comment]
Hi @nebrelbug ,
thanks for your quick response :)

One thing I noticed if using ```useWith``` with ```true```:
```typescript
Sqrl.render('Hello {{name}}', {}, {useWith: true});
```
returns the global object if the corresponding key was not found on the object, although useWith is set.

**Comment by nebrelbug** [comment]
@kerosin yes, this is expected behavior. It makes it possible to use variables from helpers, like:

```handlebars
{{@each(it.somearray) => val, index}}
Display this
The current array element is {{val}}
The current index is {{index}}
{{/each}}
```

I'll make sure to explain this in the docs too :)
