### ISSUE TITLE
Own Error handler if given data is invalid

### ISSUE THREAD

**Issue by kerosin** [squirrellyjs/squirrelly#190]
**Is your feature request related to a problem? Please describe.**
Currently squirrelly throws an exception if invalid data has been passed to```Sqrl.render```, which is totally fine as default.

**Describe the solution you'd like**
It would be great to have the possibility to define a custom error handler, which might return a result instead of throwing

e.g.
```typescript
Sqrl.render('Hello {{person.name}}', {person: null}, {useWith: true});
Sqrl.render('{{greeting}} {{person.name}}', {greeting: 'Hello'}, {useWith: true});
```
-> could both return ```'Hello '```

**Comment by nebrelbug** [comment]
@kerosin great question! Some simple error handling is possible with the `try` helper.

See https://runkit.com/nebrelbug/squirrelly-try-catch for an example :)
