### ISSUE TITLE
No doc or examples on how to make a layout in v8?

### ISSUE THREAD

**Issue by Arturace** [squirrellyjs/squirrelly#196]
I've been searching all sorts of places to find some example for v8 layouts, can't fine much. The closest thing I found was [this](https://github.com/squirrellyjs/squirrelly/issues/106#issuecomment-567584969), but I don't even know if this is the final syntax, but apparently it is implemented?

The [docs](https://squirrelly.js.org/docs/api/templates-partials-layouts/#defining-partials) aren't helpful either, on the page that should contain the info, there is only the partials example.

**Comment by Arturace** [comment]
Overall, the docs seem to be incomplete or unfinished...

**Comment by Arturace** [comment]
I have finally found it! [test/templates](https://github.com/squirrellyjs/squirrelly/tree/master/test/templates) had it all!

**Comment by nebrelbug** [comment]
@Arturace glad you found it! Sorry about the poor documentation on that front.

**Comment by lukereed1993** [comment]
@nebrelbug Some proper documentation on this would be great as it's a really useful feature and I can't find anywhere where it's properly explained. I had to find this closed issue to figure it all out.

**Comment by lukeinage** [comment]
@nebrelbug Some proper documentation on this would be great as it's a really useful feature and I can't find anywhere where it's properly explained. I had to find this closed issue to figure it all out.

**Comment by nebrelbug** [comment]
@lukeinage sorry about that, you're right! I definitely need to update the documentation to explain this.

Hopefully I'll get to that this week :crossed_fingers:
