### ISSUE TITLE
When using sqrl.templates.define() I get an error

### ISSUE THREAD

**Issue by futurelucas4502** [squirrellyjs/squirrelly#199]
**Describe the bug**

When using the following snippet of code:
```js
Sqrl.templates.define("head", Sqrl.render("views/partials/head.squirelly"));
```

I believe the reason for this error is because [here](https://github.com/squirrellyjs/squirrelly/blob/master/dist/squirrelly.cjs.js#L705) `template` is being defined as a variable and then `template()` is being called as if its a function however because we now have a function and a variable with the same name javascript interprets the word template as a variable and throws an error, therefore, I would suggest renaming the template function to `templateFunc` to fix this problem

Environment: Node

**Comment by nebrelbug** [comment]
@futurelucas4502 thanks for submitting this! I like the idea to name `template` to `templateFunc`.

Actually, though, the reason your code errors is because you should define the partial as a compiled template function, which you get using `compile`.

Here's an example that should work (though I haven't tested it)

```js
var path = require("path")

var headPartial = fs.readFileSync(path.join(__dirname, "views/partials/head.squirrelly"))

Sqrl.templates.define("head", Sqrl.compile(headPartial))
```

**Comment by nebrelbug** [comment]
@futurelucas4502 oops, I forgot that `readFileSync` returned a buffer. Glad you were able to get it working :smiley:

By the way, if you use `{{@includeFile() /}}`, you don't even have to register the partial ahead of time.

Example (again, off the top of my head, haven't tested it):
```js
let template = "{{@includeFile('partials/head.squirrelly') /}}"

Sqrl.render(template, data, {
  views: [path.join(__dirname, views)], // Tell Squirrelly where to look for the templates
  root: path.join(__dirname, views) // Not necessary in your case, but tells Squirrelly where to resolve templates w/ absolute paths
})
```

**Comment by futurelucas4502** [comment]
Hi there that would make my code a lot neater thank you I'm going to implement that now 

also if you're wondering why I'm having so many issues its because I'm building a template view renderer for electron

**Comment by nebrelbug** [comment]
@futurelucas4502 awesome, it looks really cool!
