### ISSUE TITLE
An error can occur if no data is passed to renderFile() as no check is done to see if data is defined

### ISSUE THREAD

**Issue by futurelucas4502** [squirrellyjs/squirrelly#200]
**Describe the bug**

When using renderFile if the data parameter is not passed it can cause an error as there is no check to see if it is undefined.

Changing [this](https://github.com/squirrellyjs/squirrelly/blob/master/dist/squirrelly.cjs.js#L1062-L1076) section of code to the following ensures no error will occur:
```js
    if (data != undefined){
        if (data.settings) {
            // Pull a few things from known locations
            if (data.settings.views) {
                Config.views = data.settings.views;
            }
            if (data.settings['view cache']) {
                Config.cache = true;
            }
            // Undocumented after Express 2, but still usable, esp. for
            // items that are unsafe to be passed along with data, like `root`
            var viewOpts = data.settings['view options'];
            if (viewOpts) {
                copyProps(Config, viewOpts);
            }
        }
    } 
``` 

**Environment:** Node

**Comment by nebrelbug** [comment]
Good catch! I never thought about that possibility.

In order to reduce code size, we could even change

```js
function renderFile(filename, data, cb) {
    var Config = getConfig(data || {});
```
to
```js
function renderFile(filename, data, cb) {
	data = data || {}
    var Config = getConfig(data);
```

Do you want to submit a PR with the change?

**Comment by futurelucas4502** [comment]
Good idea I didn't even think about that and sure I'll do a pull request in just a sec

**Comment by futurelucas4502** [comment]
What version of yarn is being used classic or yarn 2?

**Comment by nebrelbug** [comment]
Yarn classic
