### ISSUE TITLE
Missing null filter?

### ISSUE THREAD

**Issue by Indribell** [squirrellyjs/squirrelly#209]
When data consists of the following:

> {"ID":18,"firstname":"Jef","lastname":"","age":null}

```js
    <ul class='list'>
    {{@foreach(it.data) => key, val}}
        <li class='item'>{{key}} - {{val.firstname}} - {{val.age}}</li>
    {{/foreach}}
    </ul>
```

The result will be displayed as:

```
20 - Dirk - 14
21 - Jef - null
```

Is there no filter to automatically remove "null" from being displayed?

**Comment by nebrelbug** [comment]
@Indribell good question! The best way is probably to define a default filter:

```js
Sqrl.filters.define("default", function (val) {
  if (val === null) {
    return ""
  } else {
    return val
  }
})

Sqrl.defaultConfig.defaultFilter = "default"
```

Let me know if this solves your problem!

**Comment by Indribell** [comment]
@nebrelbug 

This works perfectly. It may be interesting to add this to the documentation for other people to find?
