### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [squirrellyjs/squirrelly#217]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by karlrudd** [comment]
The creator is currently away. I believe https://www.codeshelter.co/ now has the power to vet contributions. Please see #210 for further details.

**Comment by agustingianni** [comment]
Thank you @karlrudd I will get in contact with them.
