### ISSUE TITLE
Run browser compatibility tests

### ISSUE THREAD

**Issue by nebrelbug** [squirrellyjs/squirrelly#45]
Squirrelly tries not to use any ES6 or experimental syntax, so it should hopefully work in most (all?) browsers. Just in case, however, we need to run more comprehensive compatibility tests. There's a chance we might have forgotten some relatively new syntax, or some obscure IE bug.

## For a good pull request:
- Test Squirrelly in multiple browsers, preferably older ones
- Create a compatibility table in the ReadMe

Comment below if you want to work on this issue.

**Comment by mbo2olivier** [comment]
Hello,
squirrelly throw an syntax error on IE11 because of "const" keyword.

**Comment by mbo2olivier** [comment]
@nebrelbug  thank you very much, you will greatly relieve me.
it's been hours that I try to configure webpack and Babel to recompile squirrelly.js but without success.

**Comment by nebrelbug** [comment]
@mbo2olivier no problem! Expect a release within 10 hrs, and hopefully sooner :)

**Comment by nebrelbug** [comment]
@mbo2olivier just released v7.7.0 with the fix 😃
