### ISSUE TITLE
Make an example project, using Squirrelly, for beginners

### ISSUE THREAD

**Issue by nebrelbug** [squirrellyjs/squirrelly#65]
A good project would be fairly simple, and well commented.
Steps:
1. Create new project using Squirrelly
   * It could use Express, or run as a web page, or something else
2. Upload project to Github
3. Comment here with the link--we'll probably put it in `cheatsheet.md` or the online docs or wiki

**Comment by Jayadev6191** [comment]
@nebrelbug  Can I take this ?

**Comment by nebrelbug** [comment]
@Jayadev6191 that would be great!

**Comment by nebrelbug** [comment]
@Jayadev6191 do you have any questions?

**Comment by nebrelbug** [comment]
@Jayadev6191 I actually just found a bug with Squirrelly and Express ☹️. Hopefully I'll have it fixed by tomorrow, but pause on your repo until then. Thanks!

**Comment by Jayadev6191** [comment]
No worries. Thanks for letting me know!

**Comment by nebrelbug** [comment]
Hi @Jayadev6191! I just pushed changes that should fix the problem (along with adding caching, which should make everything a lot faster) to the `fsprob` branch.

After a little more testing, I'll merge the changes to master and publish a new version on NPM, hopefully by the end of tomorrow. At that point, you'll be able to work on it :)

**Comment by Jayadev6191** [comment]
Hi @nebrelbug great! Please let me know once you publish it :) 
Also, can you explain how that bug that you are trying to fix is blocking me from making additional changes ?

**Comment by Jayadev6191** [comment]
Hi @nebrelbug  sounds great! I will continue working on the example project without the beta. Thanks! :)

**Comment by nebrelbug** [comment]
@Jayadev6191 I just published version `6.0.1`. Working with Squirrelly and Express should be lots easier now--just follow the instructions here: [https://expressjs.com/en/guide/using-template-engines.html](https://expressjs.com/en/guide/using-template-engines.html) but with Squirrelly. Thanks!

**Comment by Jayadev6191** [comment]
Thank you sir! Will work on this today and tomorrow.

**Comment by Jayadev6191** [comment]
@nebrelbug The changes you made for the package(to make it work on express) expects the template files to have any specific extension (for e.g <temaplate_name.sqrl>) ? Please confirm. I made changes to my main file to have a view engine and passed Sqrl object to it.

`
let express = require('express');
let path = require('path');
let Sqrl = require("squirrelly");
let app = express();

app.set('view engine', Sqrl)
app.set('views', path.join(__dirname, 'views'))
`
Please let me know if this is the right way to set the template engine for squirrelly.

**Comment by nebrelbug** [comment]
That looks good! It expects files to have the extension `.squirrelly`, so for example `index.squirrelly`. I know you can just do `app.set('view engine', 'squirrelly')`, but your way might work too. You should also just be able to `app.set('views', './views')`. Thanks!

**Comment by nebrelbug** [comment]
@jeanha124 do you need any help? Here's a link that might be useful: https://squirrelly.js.org/recipes/squirrelly-with-expressjs. Thank you!

**Comment by nebrelbug** [comment]
Sorry @Jayadev6191!

**Comment by saeedcs** [comment]
How do we include one template file into another, any assistance in this matter will be appreciated

**Comment by hrsetyono** [comment]
Hi just want to contribute an example as a non-Node developer:

https://codepen.io/hrsetyono/pen/gOOZWgW

This basic usage in HTML is missing in the Learn section. We might think it's obvious how to do it, but lots of beginners will find this easier to grasp.

**Comment by nebrelbug** [comment]
@hrsetyono this is great! Would you like to put together a pull request to add this to the docs?

If not I'll add it, probably under Resources / Examples :smiley:

**Comment by hrsetyono** [comment]
@nebrelbug Glad you like it. Feel free to add it to the Resources / Examples
